### ISSUE TITLE
NameError: name 'contours' is not defined

### ISSUE THREAD

**Issue by Karthikeshwar1** [radonys/fingertrack#4]
I am getting this error :

```
Traceback (most recent call last):
  File ".../fingertrack/detect_single_threaded.py", line 73, in <module>
    contours
NameError: name 'contours' is not defined
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
```

How to get around this error?

**Comment by Karthikeshwar1** [comment]
> I am getting this error :
> 
> ```
> Traceback (most recent call last):
>   File ".../fingertrack/detect_single_threaded.py", line 73, in <module>
>     contours
> NameError: name 'contours' is not defined
> [ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
> ```
> 
> How to get around this error?

I solved it by adding the following code :

```
contours, hierarchy = cv2.findContours(thresh1.copy(), \
                                                      cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
```

on top of :

```
        if version == '3':
            contours, hierarchy = cv2.findContours(thresh1.copy(), \
                cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
        elif version == '2':
            contours, hierarchy = cv2.findContours(thresh1.copy(),cv2.RETR_TREE, \
                cv2.CHAIN_APPROX_NONE)
```
